extend-select = [
    "E",
    "F",
    "I",
    "W",
    "PLC",
    "PLE",
    "PLW",
    # "PLR",  # TODO: enable?
]

ignore = [
    "E731",
    "E741",
    "PLW2901",  # TODO: do not ignore?
    "PLW3301",  # TODO: do not ignore?
]

[per-file-ignores]
"pygal/__init__.py" = [
    "E402",
    "F401",
]
